apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-oqqq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-oqqq
    app.kubernetes.io/part-of: cin4s-839-0071-app
  name: devfile-sample-oqqq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-oqqq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-oqqq
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0071-tenant/cin4s-839-0071-app/devfile-sample-oqqq@sha256:81eae49167231de6221b71db7a085c0b093f3b9ee86dda4613bb59ce14227bed
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
